Revert "Don't convert email encoding when archiving"
This was not adequately tested, and causes errors in
lists.sr.ht-process:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/listssrht/process.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/listssrht/process.py", line 547, in dispatch_message
    msgid = mail.get("Message-ID").strip()
AttributeError: 'NoneType' object has no attribute 'strip'

This reverts commit d85758f832558863cab1da6f0742b92c66b29ae7.