Revert "Encode e-mails to base64 for Celery"
This was not adequately tested, and causes errors in
lists.sr.ht-process:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/listssrht/process.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/listssrht/process.py", line 547, in dispatch_message
    msgid = mail.get("Message-ID").strip()
AttributeError: 'NoneType' object has no attribute 'strip'

This reverts commit e3966d260cc2b8914413cce9d93f6e00f0cb3bbb.